-- =====================================================
-- SAMPLE QUERIES FOR MUSIC STORE ANALYTICS
-- =====================================================
-- This file contains example queries for all 18 views
-- Run these to explore the data and generate insights
-- =====================================================

-- =====================================================
-- 1. MONTHLY SALES TREND
-- =====================================================
-- What: Revenue, invoice count, average invoice value over time
-- Use: Track seasonality and growth

SELECT * FROM vw_monthly_sales
ORDER BY year_month DESC
LIMIT 12;

-- =====================================================
-- 2. GENRE PERFORMANCE
-- =====================================================
-- What: Revenue and units sold by genre with percentage of total
-- Use: Identify which genres drive the most revenue

SELECT genre_name, total_revenue, revenue_percentage, total_units_sold
FROM vw_sales_by_genre
ORDER BY total_revenue DESC;

-- =====================================================
-- 3. TOP 10 TRACKS
-- =====================================================
-- What: Best-selling tracks by revenue and quantity
-- Use: Identify top products for inventory decisions

SELECT track_name, artist_name, genre_name, total_revenue, revenue_rank
FROM vw_top_tracks
WHERE revenue_rank <= 10;

-- =====================================================
-- 4. TOP 10 CUSTOMERS (VIPs)
-- =====================================================
-- What: Highest spending customers with full details
-- Use: VIP treatment, loyalty programs, personalized marketing

SELECT customer_id, first_name, last_name, country, total_spent, total_invoices, days_since_last_purchase
FROM vw_top_customers;

-- =====================================================
-- 5. CUSTOMER SEGMENTATION
-- =====================================================
-- What: RFM-based customer grouping
-- Use: Targeted marketing campaigns

SELECT customer_segment, COUNT(*) AS customer_count
FROM vw_customer_segmentation
GROUP BY customer_segment
ORDER BY customer_count DESC;

-- =====================================================
-- 6. HIGH-RISK CHURN CUSTOMERS
-- =====================================================
-- What: Customers at risk of churning (6+ months inactive)
-- Use: Re-engagement campaigns

SELECT customer_id, first_name, last_name, country, days_since_last_purchase
FROM vw_churn_risk
WHERE churn_risk_level = 'High Risk (6+ months)'
ORDER BY days_since_last_purchase DESC;

-- =====================================================
-- 7. REPEAT PURCHASE RATE
-- =====================================================
-- What: Repeat purchase percentage overall and by country
-- Use: Measure customer loyalty

SELECT * FROM vw_repeat_purchase_rate
ORDER BY repeat_rate_percent DESC;

-- =====================================================
-- 8. SALES AGENT PERFORMANCE
-- =====================================================
-- What: Revenue generated by each sales agent
-- Use: Performance evaluation and coaching

SELECT first_name, last_name, customers_served, total_revenue_generated, revenue_rank
FROM vw_employee_performance
ORDER BY revenue_rank;

-- =====================================================
-- 9. ALBUM PERFORMANCE
-- =====================================================
-- What: Top albums by revenue
-- Use: Identify successful album releases

SELECT album_title, artist_name, total_revenue, revenue_rank
FROM vw_album_performance
WHERE revenue_rank <= 10;

-- =====================================================
-- 10. ARTIST REVENUE
-- =====================================================
-- What: Top artists by revenue
-- Use: Artist contract negotiations, marketing allocation

SELECT artist_name, total_revenue, total_units_sold, album_count
FROM vw_artist_revenue
LIMIT 10;

-- =====================================================
-- 11. SALES BY COUNTRY
-- =====================================================
-- What: Revenue and customer count by country
-- Use: Geographic expansion strategy

SELECT billing_country, total_revenue, customer_count, invoice_count
FROM vw_sales_by_country
ORDER BY total_revenue DESC;

-- =====================================================
-- 12. DAILY SALES TREND
-- =====================================================
-- What: Daily revenue with 7-day rolling average
-- Use: Short-term performance monitoring

SELECT invoice_date, daily_revenue, rolling_7_day_avg, cumulative_revenue
FROM vw_sales_trend
ORDER BY invoice_date DESC
LIMIT 30;

-- =====================================================
-- 13. SALES BY MEDIA TYPE
-- =====================================================
-- What: Revenue by media format (MPEG, AAC, etc.)
-- Use: Format preference analysis

SELECT media_type_name, total_revenue, revenue_percentage
FROM vw_sales_by_media_type
ORDER BY total_revenue DESC;

-- =====================================================
-- 14. MONTHLY NEW CUSTOMERS
-- =====================================================
-- What: New customer acquisition per month
-- Use: Marketing effectiveness measurement

SELECT * FROM vw_monthly_new_customers
ORDER BY acquisition_month DESC;

-- =====================================================
-- 15. GENRE LOYALTY ANALYSIS
-- =====================================================
-- What: Average invoices per customer by genre
-- Use: Identify which genres drive loyalty

SELECT genre_name, total_customers, avg_invoices_per_customer
FROM vw_repeat_genre_analysis
ORDER BY avg_invoices_per_customer DESC;

-- =====================================================
-- 16. INVOICE SUMMARY
-- =====================================================
-- What: Revenue by year, quarter, month
-- Use: High-level business reviews

SELECT year, quarter, month, invoice_count, total_revenue, avg_revenue
FROM vw_invoice_summary
ORDER BY year DESC, quarter DESC, month DESC;

-- =====================================================
-- 17. MASTER INVOICE DETAIL (Sample)
-- =====================================================
-- What: Every invoice line with full context
-- Use: Drill-down analysis

SELECT invoice_id, customer_first_name, customer_last_name, track_name, genre_name, line_total
FROM vw_invoice_detail
ORDER BY invoice_date DESC
LIMIT 20;

-- =====================================================
-- 18. CUSTOMER LIFETIME VALUE (Detailed)
-- =====================================================
-- What: Complete CLV data with recency
-- Use: Customer value analysis

SELECT customer_id, first_name, last_name, country, total_spent, total_invoices, days_since_last_purchase, spending_rank
FROM vw_customer_lifetime_value
WHERE total_spent IS NOT NULL
ORDER BY spending_rank
LIMIT 20;

-- =====================================================
-- BONUS: COMBINED INSIGHTS FOR EXECUTIVE DASHBOARD
-- =====================================================

-- KPI Summary
SELECT 'Total Revenue' AS KPI, CONCAT('$', FORMAT(SUM(total), 2)) AS Value FROM invoice
UNION ALL
SELECT 'Total Customers', FORMAT(COUNT(*), 0) FROM customer
UNION ALL
SELECT 'Total Invoices', FORMAT(COUNT(*), 0) FROM invoice
UNION ALL
SELECT 'Avg Invoice', CONCAT('$', FORMAT(AVG(total), 2)) FROM invoice
UNION ALL
SELECT 'Repeat Rate', CONCAT(FORMAT(
    (SELECT COUNT(DISTINCT customer_id) FROM invoice GROUP BY customer_id HAVING COUNT(*) > 1) 
    / (SELECT COUNT(DISTINCT customer_id) FROM customer) * 100, 1), '%');

-- Top Genre
SELECT genre_name, CONCAT(revenue_percentage, '%') AS Share
FROM vw_sales_by_genre
ORDER BY total_revenue DESC
LIMIT 1;

-- Top Country
SELECT billing_country, CONCAT('$', FORMAT(total_revenue, 2)) AS Revenue
FROM vw_sales_by_country
ORDER BY total_revenue DESC
LIMIT 1;

-- High Risk Customers Count
SELECT COUNT(*) AS High_Risk_Customers
FROM vw_churn_risk
WHERE churn_risk_level = 'High Risk (6+ months)';
